version: "3"

services:
  ceph:
    privileged: true
    restart: always
    image: quay.io/ceph/demo:main-985bb83-main-centos-arm64-stream8-aarch64 # for ARM
    # image: quay.io/ceph/demo # alternative image not for ARM 
    command: demo
    environment:
      MON_IP: 192.168.55.2
      CEPH_PUBLIC_NETWORK: 192.168.55.0/24
      LANG: en_US.utf8
      OSD_TYPE: directory
    volumes:
      - ceph-conf:/etc/ceph
    networks:
      ceph-net-tst:
        ipv4_address: "192.168.55.2"
  api-test:
    depends_on:
      - ceph
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
    restart: always
    volumes:
      - ceph-conf:/etc/ceph
    networks:
      ceph-net-tst:
        ipv4_address: "192.168.55.3"
    build:
      context: .
      dockerfile: ./test/Dockerfile

volumes:
  # volume to share ceph creds between services
  ceph-conf:
    driver: local
    driver_opts:
      o: "size=128m,uid=1000"
      device: tmpfs
      type: tmpfs
networks:
  ceph-net-tst:
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
